site_name: 路依依的随心记
theme:
  name: material
  language: zh
  logo: logo.png
  favicon: favicon.png
  features:
    - navigation.tabs

markdown_extensions:
  - meta
  - admonition
  - pymdownx.superfences
  - pymdownx.tilde:
      smart_delete: false
      subscript: false

extra_css:
  - stylesheets/extra.css

nav:
  - 主页: index.md
  - 课程:
      - 课程首页: course/index.md
      - 示例文档: course/example.md
  - 资源:
      - 首页: resources/index.md
      - zju-connect+ClashVergeRev: resources/zju-connect-clash.md
  - 杂记:
      - 杂记首页: zaji/index.md
      - 宜州: zaji/Yizhou.md
  - 关于: about/index.md
  - 友链: friends/index.md